openapi: 3.0.0
info:
  description: >
    Dette er APIene til Knowit dataplattform

    [https://github.com/knowit/Dataplattform](https://github.com/knowit/Dataplattform)
  version: "1.0.0-oas3"
  title: Knowit dataplattform
tags:
  - name: docs
    description: Fetch alle dokumenter for en type
paths:
  '/get_docs/{type}':
    get:
      tags:
        - docs
      summary: Henter rå data ved hjelp av type (og timestamps om du vil)
      description: Svaret du får fra denne requesten er en url som du igjen må requeste. Dette kan virke litt teit, men det er slik man må gjøre for å komme seg over 6MB grensen AWS Lambda payloads har. Du må være authorized for å kjøre denne (trykk på hengelåsen over).
      operationId: findPetsByStatus
      parameters:
        - name: timestamp_from
          in: query
          description: Timestamp fra når du vil hente ut docsene.
          required: false
          schema:
            type: integer
            format: int32
        - name: timestamp_to
          in: query
          description: Timestamp til.
          required: false
          schema:
            type: integer
            format: int32
        - name: just_url
          in: query
          description: Sett denne til true om du vil bare få tak i URLen og ikke de 25 nyeste datapunktene.
          required: false
          schema:
            type: boolean
        - name: type
          in: path
          description: Hva slags datatype du vil hente ut.
          required: true
          explode: true
          schema:
            type: string
            enum:
              - GithubType
              - SlackType
              - EventRatingType
              - EventType
              - UBWType
            default: SlackType
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Raw_doc'
            
        '400':
          description: Invalid status value
servers:
  - url: 'https://ji54uhowf8.execute-api.eu-central-1.amazonaws.com/dev'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Category
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          format: int32
          description: User Status
      xml:
        name: User
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    Raw_doc:
      type: object
      required:
        - id
        - type
        - timestamp
        - data
      properties:
        id:
          type: string
          example: AAAAAF0Z6ZUq4p/32Dka/Q==
        type:
          type: string
          example: GithubType
        timestamp:
          type: integer
          example: 1562055759
        data:
          type: string
          example: '{"commit_id: "123abc", repository: "name:": "knowit/dataplattform"}'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
security:
  - api_key: []