service: dataplattform-layers

custom:
  stage: ${opt:stage, self:provider.stage}
  project: Dataplattform-${self:custom.stage}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  tags:
    Project: ${self:custom.project}

layers:
  TimestampRandom:
    path: timestamp_random
    name: ${self:custom.stage}-timestamp_random
    description: Generate unique ids
    compatibleRuntimes:
      - python3.7

resources:
  Outputs:
    TimestampRandomArn:
      Value:
        Ref: TimestampRandomLambdaLayer
      Export:
        Name: ${self:custom.project}-layer-timestamprandom-arn
